### ISSUE TITLE
trying it out....

### ISSUE THREAD

**Issue by devcurmudgeon** [ssssam/software-dependency-visualizer#3]
On MacOS I had to 

```
brew install python3
sudo python3 -m pip install pyyaml neo4jrestclient bottle
```

After that when I ran the server i got...

~/Projects/2016/software-dependency-visualizer>python3 ./server.py 
Traceback (most recent call last):
  File "./server.py", line 50, in <module>
    database = neo4jrestclient.client.GraphDatabase(args.neo4j)
  File "/usr/local/lib/python3.5/site-packages/neo4jrestclient/client.py", line 79, in __init__
    response = Request(**self._auth).get(self.url)
  File "/usr/local/lib/python3.5/site-packages/neo4jrestclient/request.py", line 63, in get
    return self._request('GET', url, headers=headers)
  File "/usr/local/lib/python3.5/site-packages/neo4jrestclient/request.py", line 200, in _request
    raise StatusException(401, "Authorization Required")
neo4jrestclient.exceptions.StatusException: Code [401]: Unauthorized. No permission -- see authorization schemes.
Authorization Required

**Comment by palvarez89** [comment]
could you move the issue to https://github.com/CodethinkLabs/software-dependency-visualizer? I was going to do it myself, but then thought you won't get any notifications..


Thanks

**Comment by devcurmudgeon** [comment]
yup...
